server:
  port: 9088
  http:
    port: 1010
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: REST-client/src/main/resources/tls/keystore.p12
    key-store-password: keyStoreSecret
    key-alias: tomcat
management:
  endpoint:
    health:
      show-details: always
oauth:
  client-id: trusted-client
  client-secret: trusted-client-secret
  username: admin
  password: 123456