server:
  port: 9091

###
# Database credentials for MySQL
###
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_services?allowPublicKeyRetrieval=true&useSSL=false
    username: service
    password: service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        show_sql: true
        hbm2ddl:
          auto: update
        generate-ddl: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

###
# Security configuration
###
security:
  oauth2:
    resource:
      accessTokenUri: http://localhost:9091/oauth/token